import { NextPage } from "next";
import Head from "next/head";
import LandingPageTemplate from "../templates/LandingPage/LandingPageTemplate";
import { UndanganPageTemplate } from "@/templates/UndanganPage/UndanganPageTemplate";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>hanimarkus</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <UndanganPageTemplate />
      {/* <LandingPageTemplate /> */}
    </>
  );
};

export default Index;
